/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rifaldy
 */
public class app extends javax.swing.JFrame {
    //1 : socket am4
    //2 : socket 1151 lga
    private int[] hargaCpu = {0,2500000,3300000,5100000,1400000,2800000,4500000};
    private String[] amd = {"asrock a320m", "asrock b450m steel legend","asrock x570 taichi"};
    private ArrayList<String> psu =  new ArrayList();
    private String[] intel = {"asrock h110 m","msi h310 pro","msi b365m pro"};
    private int[] hargaAmd = {750000,1600000,5700000};
    private int[] hargaIntel ={720000,1050000,1160000};
    private int[] hargaVga= {3500000,4200000,5800000,9000000,12800000};
    private int[] hargaRam= {300000,400000,600000,750000,12000000,1400000};
    private int[] hargaPsu={600000,760000,2000000};
    private int[] hargaPenyimpanan = {170000,600000,620000,980000};
    private int pilihan = 0;
    int harga = 0;
    
    private void set(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Processor");
        model.addColumn("Mobo");
        model.addColumn("VGA");
        model.addColumn("ram");
        model.addColumn("PSU");
        model.addColumn("Disk");
        model.addColumn("Harga");
        model.addColumn("Kode Unik");
        
        try{
            int no = 1;
            String sql = "select * from rakit";
            java.sql.Connection con = (Connection)Conn.configDB();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet res= st.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9)});
            }
            tables.setModel(model);
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void set(int param){
        
        if (param > 0 && param < 4){
            pilihan = 1;
            for(int i=0; i <= amd.length-1;i++){
                cbMobo.addItem(amd[i]);
            }
        }else if(param >=4 ){
            pilihan = 2;
            for(int i=0; i <= intel.length-1;i++){
                cbMobo.addItem(intel[i]);
            }
                    
        }else{
            pilihan = 0;
        }
            
        
    }
    private void hitungHarga(){
        System.out.println(pilihan);
        int harga_mobo = 0;
        if (pilihan == 1){
            harga_mobo = hargaAmd[cbMobo.getSelectedIndex()];
        }else if(pilihan == 2){
            harga_mobo = hargaIntel[cbMobo.getSelectedIndex()];
            
        }
        harga = hargaCpu[cbProcessor.getSelectedIndex()]+harga_mobo+hargaVga[cbVga.getSelectedIndex()]+hargaRam[cbRam.getSelectedIndex()]+hargaPsu[cbPsu.getSelectedIndex()]+hargaPenyimpanan[cbPenyimpanan.getSelectedIndex()];
        
        txtHarga.setText(String.valueOf(harga));
    }
    private void reset(){
        cbProcessor.setSelectedIndex(0);
        cbMobo.setEnabled(false);
        set();
        btnSimpan.setEnabled(false);
    }

    /**
     * Creates new form app
     */
    public app() {
        initComponents();
        set();
        psu.add("Cooler master mwe 450");
        psu.add("Cooler master mwe 550");
        psu.add("Gamemax 1000");
        for(int i=0; i <= psu.size()-1;i++){
                cbPsu.addItem(psu.get(i));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbProcessor = new javax.swing.JComboBox<>();
        cbMobo = new javax.swing.JComboBox<>();
        cbVga = new javax.swing.JComboBox<>();
        cbRam = new javax.swing.JComboBox<>();
        cbPsu = new javax.swing.JComboBox<>();
        cbPenyimpanan = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        btnHarga = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Simulasi Perakitan Komputer");

        jLabel2.setText("Processor :");

        jLabel3.setText("Mother Board :");

        jLabel4.setText("vga :");

        jLabel5.setText("ram :");

        jLabel6.setText("PSU :");

        jLabel7.setText("penyimpanan :");

        cbProcessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "ryzen 3 3200g", "ryzen 5 3200g", "ryzen 7 3700x", "intel i3 9100", "intel i5 9400", "core i7 9700", " " }));
        cbProcessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProcessorActionPerformed(evt);
            }
        });

        cbMobo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMobo.setEnabled(false);
        cbMobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMoboActionPerformed(evt);
            }
        });

        cbVga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nvidia gtx 1050ti", "nvidia gtx 1650", "nvidia gtx 1650 super", "nvidia gtx 1080", "nvidia gtx 1080ti" }));

        cbRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single channel 4gb", "dual channel 4gb", "single channel 8gb", "dual channel 8gb", "single channel 16gb", "dual channel 16gb" }));

        cbPenyimpanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hdd 500gb", "hdd 1tb", "ssd 256gb", "ssd 500gb" }));

        txtHarga.setEditable(false);

        btnHarga.setText("cek harga");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbVga, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRam, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPsu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSimpan))
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbVga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbPsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHarga)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProcessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProcessorActionPerformed
        // TODO add your handling code here:
        int pilihan = cbProcessor.getSelectedIndex();
        cbMobo.removeAllItems();
        cbMobo.setEnabled(true);
        if(pilihan != 0){
            set(pilihan);
        }
    }//GEN-LAST:event_cbProcessorActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        // TODO add your handling code here:
        if(cbProcessor.getSelectedIndex() != 0 ){
            hitungHarga();
            btnSimpan.setEnabled(true);
        }else{
            showMessageDialog(null,"form harus lengkap");
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void cbMoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMoboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMoboActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        int kode = 0;
        Random ran = new Random();
        kode = ran.nextInt(1000000)+1;
        
         try{
            String sql = "INSERT INTO rakit (processor,mobo,vga,ram,psu,penyimpanan,harga,kode) VALUES ('"+cbProcessor.getSelectedItem()+ "','" + cbMobo.getSelectedItem() + "','" + cbVga.getSelectedItem()+ "','" + cbRam.getSelectedItem()+ "','" + cbPsu.getSelectedItem()+ "','" + cbPenyimpanan.getSelectedItem() + "'," + txtHarga.getText()  + ",'" + String.valueOf(kode) +"')";
            java.sql.Connection con = (Connection)Conn.configDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            showMessageDialog(null,"berhasil memasukan data");
            reset();
            
        }catch(SQLException e){
            showMessageDialog(null,"gagal memasukan data");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbMobo;
    private javax.swing.JComboBox<String> cbPenyimpanan;
    private javax.swing.JComboBox<String> cbProcessor;
    private javax.swing.JComboBox<String> cbPsu;
    private javax.swing.JComboBox<String> cbRam;
    private javax.swing.JComboBox<String> cbVga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tables;
    private javax.swing.JTextField txtHarga;
    // End of variables declaration//GEN-END:variables
}
